version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hd-buildservice
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: bitnami/rabbitmq:latest
  
  build-service:
    build: .
    ports: 
      - "5002:5002"
    depends_on:
      - rabbitmq
      - db

volumes:
  database_data: